### ISSUE TITLE
Failed to install enpt on Mac M1

### ISSUE THREAD

**Issue by zxdawn** [GFZ/enpt#2]
* Operating System: Mac OS Version 13.2.1 (22D68)

### Description

Can't install enpt on Mac.

### What I Did

```
mamba create --name enpt enpt
```

Output:
```
Looking for: ['enpt']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
pkgs/main/noarch                                              No change
pkgs/main/osx-arm64                                           No change
pkgs/r/osx-arm64                                   118.0 B @ 565.0 B/s  0.2s
pkgs/r/noarch                                                 No change
Could not solve for environment specs
The following package could not be installed
└─ enpt   is uninstallable because it requires
   └─ arosics >=1.0.0 , which does not exist (perhaps a missing channel).
```

The default version of `arosics` is 0.9.24 if I run `mamba install -c conda-forge arosics`.

**Comment by danschef** [comment]
Currently, there are still some packages in the requirements of EnPT that are not yet available for osx-arm64, i.e., for Mac M1. This is a current limitation and has to be fixed by providing respective conda-forge builds.

That means that there is currently no way to install EnPT on Mac M1 at the moment, at least not from conda-forge. I will have to check which packages need to be ported exactly - if it is only arosics, then I should be able to fix this quite soon.

**Comment by zxdawn** [comment]
Thanks! Don't worry, I will use enpt on Linux machine first. Take your time.

**Comment by danschef** [comment]
After merging https://github.com/conda-forge/arosics-feedstock/pull/65 right now, the OSX ARM64 builds for arosics (required by EnPT) should become available within the next hours. This might directly enable to install EnPT on Mac M1.

@zxdawn It would be nice if you could retry the installation and report any further issues here.

**Comment by zxdawn** [comment]
Thanks a lot for your help. It works well now on M1 and M2.

**Comment by danschef** [comment]
Thanks for the feedback!
